config/routes.rb
Rails.application.routes.draw do
  resources :projects do
    resources :songs
  end
  devise_for :users
  root to: "projects#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :songs
  belongs_to :user
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :project

  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :projects
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = current_user.projects #Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    #@song = @project.songs.build
  end

  # GET /projects/new
  def new
    @project = current_user.projects.build #Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = current_user.projects.build(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = current_user.projects.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:name)
    end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project
  before_action :set_song, only: [:show, :edit, :update, :destroy]

  # GET projects/1/songs
  def index
    @songs = @project.songs
  end

  # GET projects/1/songs/1
  def show
  end

  # GET projects/1/songs/new
  def new
    @song = @project.songs.build
  end

  # GET projects/1/songs/1/edit
  def edit
  end

  # POST projects/1/songs
  def create
    @song = @project.songs.build(song_params)

    if @song.save
      redirect_to([@song.project, @song], notice: 'Song was successfully saved.')
    else
      render action: 'new'
    end
  end

  # PUT projects/1/songs/1
  def update
    if @song.update_attributes(song_params)
      redirect_to([@song.project, @song], notice: 'Song was successfully updated.')
    else
      render action: 'edit'
    end
  end

  # DELETE projects/1/songs/1
  def destroy
    @song.destroy

    redirect_to @project #project_songs_url(@project)
  end

  private
    # # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = current_user.projects.find(params[:project_id])
    end

    def set_song
      @song = @project.songs.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def song_params
      params.require(:song).permit(:name, :content, :tag, :project_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>How Did I Play That Song</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container">
      
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <div class="pt-5">
    <%= yield %>
    </div>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Projects</h1>
<%= link_to 'New Project', new_project_path %>

<ul class="nav nav-pills flex-column">
    <% @projects.each do |project| %>
      <li class="nav-item">
        <h3><%= project.name %></h3>
        <div class="project-options">
          <%= link_to 'Show', project %>
          <%= link_to 'Edit', edit_project_path(project) %>
          <%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %>
        </div>
      </li>
    <% end %>
</ul>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<p>
  <strong>User:</strong>
  <%= @project.user_id %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>


<hr>
<h1>Listing songs</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Content</th>
    <th>Tag</th>
    <th>Project</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @project.songs.each do |song| %>
    <tr>
      <td><%= song.name %></td>
      <td><%= song.content %></td>
      <td><%= song.tag %></td>
      <td><%= song.project %></td>
      <td><%= link_to 'Show', [song.project, song] %></td>
      <td><%= link_to 'Edit', edit_project_song_path(song.project, song) %></td>
      <td><%= link_to 'Destroy', [song.project, song], method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
<% end %>
</table>

<br />

<%= link_to 'New Song', new_project_song_path(@project.id) %>

app/views/songs/_form.html.erb
<%= form_for([@song.project, @song]) do |f| %>
  <% if @song.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
      <% @song.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  
  <div class="field">
    <%= f.label :tag %><br />
    <%= f.text_field :tag %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/songs/edit.html.erb
<h1>Editing song</h1>

<%= render 'form' %>

<%= link_to 'Show', [@song.project, @song] %> |
<%= link_to 'Back', project_songs_path(@song.project) %>

app/views/songs/index.html.erb
<h1>Listing songs</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Content</th>
    <th>Tag</th>
    <th>Project</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @songs.each do |song| %>
  <tr>
    <td><%= song.name %></td>
    <td><%= song.content %></td>
    <td><%= song.tag %></td>
    <td><%= song.project %></td>
    <td><%= link_to 'Show', [song.project, song] %></td>
    <td><%= link_to 'Edit', edit_project_song_path(song.project, song) %></td>
    <td><%= link_to 'Destroy', [song.project, song], method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Song', new_project_song_path(params[:project_id]) %>

app/views/songs/new.html.erb
<h1>New song</h1>

<%= render 'form' %>

<%= link_to 'Back', project_songs_path(@song.project) %>

app/views/songs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @song.name %>
</p>

<p>
  <b>Content:</b>
  <%= @song.content %>
</p>

<p>
  <b>Tag:</b>
  <%= @song.tag %>
</p>

<p>
  <b>Project:</b>
  <%= @song.project %>
</p>


<%= link_to 'Edit', edit_project_song_path(@song.project, @song) %> |
<%= link_to 'Back', project_songs_path(@song.project) %>

<hr>